### ISSUE TITLE
[Crash] CTD Sitting on Seat

### ISSUE THREAD

**Issue by Epik-B0mber** [lilypuree/Decorative-Blocks#102]
I really don't know what happened lol; I was just testing this mod with very few others loaded, right clicked one of the seats, and, there went my game.
Here's my log, I really don't know what to make heads of lol.

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-01-26 16:38:06
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraftforge/network/NetworkHooks
	at lilypuree.decorative_blocks.platform.ForgePlatformHelper$1.m_5654_(ForgePlatformHelper.java:39) ~[decorative_blocks-forge-1.20.1-4.0.2.jar%23192!/:4.0.2] {re:classloading}
	at net.minecraft.server.level.ServerEntity.m_289200_(ServerEntity.java:237) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.server.level.ServerEntity.m_8541_(ServerEntity.java:226) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap$TrackedEntity.m_140497_(ChunkMap.java:1356) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap$TrackedEntity.m_140487_(ChunkMap.java:1384) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1140) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:465) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1504) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1487) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:136) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:97) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:80) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157533_(PersistentEntitySectionManager.java:71) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8872_(ServerLevel.java:859) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_7967_(ServerLevel.java:814) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:A}
	at lilypuree.decorative_blocks.blocks.SeatBlock.m_6227_(SeatBlock.java:152) ~[decorative_blocks-forge-1.20.1-4.0.2.jar%23192!/:4.0.2] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:778) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1034) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:23) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:160) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:660) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:249) ~[client-1.20.2-20230921.100330-srg.jar%23220!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.network.NetworkHooks
	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:397) ~[securemodules-2.2.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	... 35 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 225776744 bytes (215 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 32
	Virtual memory max (MB): 36219.87
	Virtual memory used (MB): 18224.83
	Swap memory total (MB): 3712.00
	Swap memory used (MB): 54.36
	Launched Version: 1.20.2-forge-48.1.0
	ModLauncher: 10.1.1
	ModLauncher launch target: forge_client
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.2.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.1.1.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.1.1.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.1.1.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@48
		javafml@null
	Mod List: 
		client-1.20.2-20230921.100330-srg.jar             |Minecraft                     |minecraft                     |1.20.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		smoothchunk-1.20.1-3.5.jar                        |Smoothchunk mod               |smoothchunk                   |1.20.1-3.5          |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.1.0-mc1.20.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		DustrialDecor-1.3.4-1.20.jar                      |'Dustrial Decor               |dustrial_decor                |1.3.2               |DONE      |Manifest: NOSIGNATURE
		beautify-2.0.2.jar                                |Beautify                      |beautify                      |2.0.2               |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.2-mc1.20.2forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.2               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.1.1-mc1.20.2forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Grass_Overhaul-Forge-23.10.10-MC1.20.1.jar        |Grass Overhaul                |grassoverhaul                 |23.10.10            |DONE      |Manifest: NOSIGNATURE
		ThisRocks-1.20.1-1.5.1.jar                        |This Rocks! (Forge)           |rocks                         |1.5.1               |DONE      |Manifest: NOSIGNATURE
		spark-1.10.54-forge.jar                           |spark                         |spark                         |1.10.54             |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.2.1-mc1.20.2forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		gpumemleakfix-1.20.1-1.8.jar                      |Gpu memory leak fix           |gpumemleakfix                 |1.20.1-1.8          |DONE      |Manifest: NOSIGNATURE
		toomanynuggets-1.20.2-1.0.0.jar                   |Too Many Nuggets              |toomanynuggets                |1.20.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		mcw-holidays-1.1.0-mc1.20.2forge.jar              |Macaw's Holidays              |mcwholidays                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.20.1-2.1.0.jar                    |Falling Leaves                |fallingleaves                 |2.1.0               |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.5-1.20.2forge.jar               |Macaw's Paintings             |mcwpaintings                  |1.0.5               |DONE      |Manifest: NOSIGNATURE
		alternate_current-mc1.20-1.7.0.jar                |Alternate Current             |alternate_current             |1.7.0               |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.20.2-9.2.0.5.jar                  |Serene Seasons                |sereneseasons                 |9.2.0.5             |DONE      |Manifest: NOSIGNATURE
		decorative_blocks-forge-1.20.1-4.0.2.jar          |Decorative Blocks             |decorative_blocks             |4.0.2               |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0.jar                       |MixinExtras                   |mixinextras                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		AmbientEnvironment-forge-1.20.2-12.0.0.4.jar      |AmbientEnvironment            |ambientenvironment            |12.0.0.4            |DONE      |Manifest: NOSIGNATURE
		ipp-3.1.2.jar                                     |Instrument++                  |ipp                           |3.1.2               |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.2.4b-mc1.20.2forge.jar                |Macaw's Roofs                 |mcwroofs                      |2.2.4b              |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.1.0forge-mc1.20.2.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.0               |DONE      |Manifest: NOSIGNATURE
		architectury-10.0.17-minecraftforge.jar           |Architectury                  |architectury                  |10.0.17             |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.20-0.5.2.jar                    |AI-Improvements               |aiimprovements                |0.5.2               |DONE      |Manifest: NOSIGNATURE
		visuality-forge-2.0.2.jar                         |Visuality: Reforged           |visuality                     |2.0.2               |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.2.2-mc1.20.2forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.2               |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.2-2.1.jar                           |Cupboard utilities            |cupboard                      |1.20.2-2.1          |DONE      |Manifest: NOSIGNATURE
		wafflesmoss-v1.0-FORGE-1.20.1.jar                 |Waffle's Moss                 |wafflesmoss                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		cloth-config-12.0.119-forge.jar                   |Cloth Config v12 API          |cloth_config                  |12.0.119            |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.20.2-2.4.32.jar                 |Simple Voice Chat             |voicechat                     |1.20.2-2.4.32       |DONE      |Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.20.2-1.3.1.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.20.2-1.3.1        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.2-48.1.0-universal.jar                 |Forge                         |forge                         |48.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		SimpleRadio-forge-1.20.2-2.1.2.jar                |SimpleRadio                   |simpleradio                   |2.1.2               |DONE      |Manifest: NOSIGNATURE
		wafflesplaster-v1.0-FORGE-1.20.1.jar              |Waffles Plaster               |wafflesplaster                |1.0                 |DONE      |Manifest: NOSIGNATURE
		mcw-paths-1.0.4forge-mc1.20.2.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.4               |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.6-mc1.20.2forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 4169e635-fc18-4271-a15f-9cec55d11751
	FML: 48.1
	Forge: net.minecraftforge:48.1.0
```

**Comment by lilypuree** [comment]
version 4.x is not compatible with 1.20.2.

**Comment by Epik-B0mber** [comment]
Wait, how did I get ahold of this in 1.20.2?! Lol oops, user error there, my bad. Thanks! 'XD
