### ISSUE TITLE
Json Errors w/ Tags

### ISSUE THREAD

**Issue by WenXin20** [lilypuree/Decorative-Blocks#12]
Minecraft v1.15.2
Decorative Blocks v6d

I've noticed that the logs will print out a bunch of errors for missing items in tags if the mods are not installed. The values option can be changed to optional to prevent these errors.
The error can be solved by simply changing 
```
{
  "values": [
    "decorative_blocks:cherry_beam"
  ]
}
```
to 
```
{
  "optional": [
    "decorative_blocks:cherry_beam"
  ]
}
```

```
[00:38:46] [Server-Worker-11/ERROR]: Couldn't read item tag list biomesoplenty:umbran_logs from biomesoplenty:tags/items/umbran_logs.json in data pack decorative_blocks-6d.jar
com.google.gson.JsonParseException: Unknown value 'decorative_blocks:umbran_beam'
	at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:157) ~[?:?]
	at net.minecraft.tags.Tag$Builder$$Lambda$4689/1633763821.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:156) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) [?:?]
	at net.minecraft.tags.TagCollection$$Lambda$4676/1287551477.get(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
```

**Comment by lilypuree** [comment]
Thanks!
