### ISSUE TITLE
Crashes to desktop when loading into world, version 1.14.4, think its to do with the thatched roofs

### ISSUE THREAD

**Issue by frazw** [lilypuree/Decorative-Blocks#13]
I think its something to do with the fluid behavior of the hay bales, version 5 works fine
version 6 and 6b cause the crash

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 01/04/20 12:54
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluid()Lnet/minecraftforge/fluids/Fluid;
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getErrorInfo(FluidStackHelper.java:127) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getErrorInfo(FluidStackHelper.java:19) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.util.ErrorUtil.getIngredientInfo(ErrorUtil.java:123) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.util.ErrorUtil.getIngredientOutputInfo(ErrorUtil.java:79) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.util.ErrorUtil.getInfoFromRecipe(ErrorUtil.java:63) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.recipes.RecipeManager.addRecipe(RecipeManager.java:140) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.recipes.RecipeManager.addRecipeTyped(RecipeManager.java:93) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.recipes.RecipeManager.addRecipes(RecipeManager.java:86) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.recipes.RecipeManager.<init>(RecipeManager.java:78) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:144) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:76) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:125) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:103) ~[?:6.0.0.10] {re:classloading}
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$3108/741754288.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$1990/168947686.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:1001) ~[?:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1268) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$4642/1056295862.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.56.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$385/649630909.call(Unknown Source) [forge-1.14.4-28.1.56.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getErrorInfo(FluidStackHelper.java:127)
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getErrorInfo(FluidStackHelper.java:19)
	at mezz.jei.util.ErrorUtil.getIngredientInfo(ErrorUtil.java:123)
	at mezz.jei.util.ErrorUtil.getIngredientOutputInfo(ErrorUtil.java:79)
	at mezz.jei.util.ErrorUtil.getInfoFromRecipe(ErrorUtil.java:63)
	at mezz.jei.recipes.RecipeManager.addRecipe(RecipeManager.java:140)
	at mezz.jei.recipes.RecipeManager.addRecipeTyped(RecipeManager.java:93)
	at mezz.jei.recipes.RecipeManager.addRecipes(RecipeManager.java:86)
	at mezz.jei.recipes.RecipeManager.<init>(RecipeManager.java:78)
	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:144)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:76)
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:125)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:103)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$3108/741754288.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$1990/168947686.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:1001)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1268)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15)
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33)
	at net.minecraft.network.PacketThreadUtil$$Lambda$4642/1056295862.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['DrTwiglet'/251, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: Client Chunk Cache: 1849, 0
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$385/649630909.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 872272120 bytes (831 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.56.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.56.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.56.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.56.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.56.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.56
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		carpetstairsmod-mc1.14-v1.3.2.jar Carpet Stairs Mod {carpetstairsmod@1.3.2 DONE}
		create-mc1.14.4_v0.2.2a.jar Create {create@mc1.14-0.2.2a DONE}
		decorative_blocks_6.jar Decorative Blocks {decorative_blocks@1.5 DONE}
		jei-1.14.4-6.0.0.10.jar Just Enough Items {jei@6.0.0.10 DONE}
		mcw-furniture-1.0.1-mc1.14.4.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		pamhc2crops-1.14.4-1.0.4.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		pamhc2trees-1.14.4-1.0.0.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		forge-1.14.4-28.1.56-universal.jar Forge {forge@28.1.56 DONE}
		forge-1.14.4-28.1.56-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.1.56
	LWJGL: 3.2.2 build 10
	OpenGL: Radeon (TM) RX 480 Graphics GL version 4.6.13572 Compatibility Profile Context 19.11.3 26.20.13031.18002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Better+Leaves+Add-on+V2.2-1.14.zip, file/JermsyBoy's+Vanilla+Edits+V1.2-1.14.zip, mod_resources
	Current Language: English (United Kingdom)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13572 Compatibility Profile Context 19.11.3 26.20.13031.18002
	OpenGlRenderer: Radeon (TM) RX 480 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by lilypuree** [comment]
Update to the latest version of JEI (6.0.0.27).
