### ISSUE TITLE
[Fabric 1.20.4] Crashed on startup

### ISSUE THREAD

**Issue by kingkuys2123** [lilypuree/Decorative-Blocks#98]
Minecraft 1.20.4
Fabric 0.15.3
Fabric API 0.92.1
Java 20.0.2
Decorative Blocks 4.0.0

## **ISSUES**
 - Crashed when I tried to launch MC with Decorative Blocks installed
 - Prolly similar to #97 but I don't have BCLib and BetterNether installed, and I am on 1.20.4

## **CRASH LOG**
Full Crash Log: https://pastebin.com/Zn5Mm78z
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-01-06 16:08:49
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'decorative_blocks'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(A world now silent:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_2533.<init>(net.minecraft.class_4970$class_2251, net.minecraft.class_8177)'
	at lilypuree.decorative_blocks.blocks.BarPanelBlock.<init>(BarPanelBlock.java:30)
	at lilypuree.decorative_blocks.core.DBBlocks.lambda$static$12(DBBlocks.java:67)
	at lilypuree.decorative_blocks.registration.fabric.FabricRegistrationFactory$Provider.register(FabricRegistrationFactory.java:111)
	at lilypuree.decorative_blocks.core.DBBlocks.registerBlock(DBBlocks.java:108)
	at lilypuree.decorative_blocks.core.DBBlocks.<clinit>(DBBlocks.java:67)
	at lilypuree.decorative_blocks.DecorativeBlocks.onInitialize(DecorativeBlocks.java:16)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more

```

**Comment by lilypuree** [comment]
4.0.0 doesn't support 1.20.4, the file was incorrectly labeled.

**Comment by kingkuys2123** [comment]
Oh okay, noted
